extensions:
  health_check: {}
  sigv4auth:
    region: ${env:AWS_REGION}

receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
  prometheus:
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: sidecar
          static_configs:
            - targets: [ "127.0.0.1:${env:METRICS_PORT}" ]
          metrics_path: /metrics

processors:
  resourcedetection:
    detectors: [env, ecs]
    timeout: 2s
  batch: {}

exporters:
  awsxray: {}
  prometheusremotewrite:
    endpoint: https://aps-workspaces.${env:AWS_REGION}.amazonaws.com/workspaces/${env:AMP_WORKSPACE_ID}/api/v1/remote_write
    auth:
      authenticator: sigv4auth
    tls:
      insecure_skip_verify: true
    external_labels:
      cluster: ecs-cluster
  debug: {}

service:
  telemetry:
    logs:
      level: warn
  extensions: [health_check, sigv4auth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [awsxray]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite, debug]
