extensions:
  health_check:
  sigv4auth:
    region: ${env:AWS_REGION}
  ecs_observer:
    cluster_name: ecs-cluster
    refresh_interval: 30s
    result_file: /etc/ecs/ecs_sd_targets.yaml
    services:
      - name_pattern: ".*(user|account|fcm|sqs|transaction)-service"
        metrics_ports: [8000]
        metrics_path: /metrics

receivers:
  otlp:
    protocols:
      grpc: {}
  prometheus:
    config:
      scrape_configs:
        - job_name: "ecs-sd"
          file_sd_configs:
            - files: [ /etc/ecs/ecs_sd_targets.yaml ]
          metrics_path: /metrics

processors:
  resourcedetection:
    detectors: [env, ecs]
    timeout: 2s
  batch: {}

exporters:
  awsxray: {}
  prometheusremotewrite:
    endpoint: https://aps-workspaces.${env:AWS_REGION}.amazonaws.com/workspaces/${env:AMP_WORKSPACE_ID}/api/v1/remote_write
    auth:
      authenticator: sigv4auth

service:
  telemetry:
    logs:
      level: warn   # 잡다한 정보 로그 억제
  extensions: [health_check, ecs_observer, sigv4auth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [awsxray]
    metrics:
      receivers: [prometheus]
      processors: [resourcedetection, batch]
      exporters: [prometheusremotewrite]
