extensions:
  health_check:
  sigv4auth:
    region: ap-northeast-2
  ecs_observer:
    cluster_name: ecs-cluster
    refresh_interval: 30s
    result_file: /etc/ecs/ecs_sd_targets.yaml

receivers:
  otlp:
    protocols: { grpc: {} }
  prometheus:
    config:
      scrape_configs:
        - job_name: ecs-sd
          file_sd_configs:
            - files: [ /etc/ecs/ecs_sd_targets.yaml ]
          metrics_path: /metrics

processors:
  batch: {}
  resourcedetection:
    detectors: [env, ecs]
    timeout: 2s

exporters:
  awsxray: {}
  awsprometheusremotewrite:
    endpoint: https://aps-workspaces.${env:AWS_REGION}.amazonaws.com/workspaces/${env:AMP_WORKSPACE_ID}/api/v1/remote_write
    auth:
      authenticator: sigv4auth
  # debug: {}  # 임시 디버깅 시만

service:
  telemetry:
    logs:
      level: warn   # ← “extracfg.txt” 같은 정보 로그 잠재움
  extensions: [health_check, ecs_observer, sigv4auth]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [awsxray]
    metrics:
      receivers: [prometheus]
      processors: [resourcedetection, batch]
      exporters: [awsprometheusremotewrite]
