receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 128
  batch:
    timeout: 2s
    send_batch_size: 512
  resourcedetection:
    detectors: [ecs, env]
    timeout: 2s
    override: true

exporters:
  awsxray: {}
  debug:    # ← 기존 logging 대신 사용
    verbosity: basic

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, batch]
      exporters: [awsxray, debug]
